mysite/ekart/urls.py
from django.conf.urls import url

from . import views

app_name = "ekart"
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<painting_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^search/', views.search, name='search'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^ekart/', include('ekart.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG is True:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/ekart/models.py
from django.db import models
import os

class Artist(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

def get_image_path(instance, filename):
	return os.path.join('paintings', str(instance.id), filename)

class Painting(models.Model):
	name = models.CharField(max_length=200)
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
	image = models.ImageField(upload_to=get_image_path, blank=True, null=True)
	price = models.DecimalField(max_digits=6, decimal_places=2)

	def save(self, *args, **kwargs):
		if self.id == None:
			saved_image = self.image
			self.image = None
			super(Painting, self).save(*args, **kwargs)
			self.image = saved_image
			#kwargs.pop('force_insert')
		super(Painting, self).save(*args, **kwargs)

	def __str__(self):
		return self.name

mysite/ekart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .models import Painting, Artist

def index(request):
	painting_list = Painting.objects.all()
	context = {'painting_list': painting_list}
	return render(request, 'ekart/index.html', context)

def detail(request, painting_id):
	painting = get_object_or_404(Painting, pk=painting_id)
	return render(request, "ekart/detail.html", {'painting': painting})

def search(request):
	txt = request.POST['t']
	painting_list = Painting.objects.filter(name__contains=txt)
	if (len(txt) == 0):
		return render(request, "ekart/index.html", {'error_message': 'Please enter some text', 'painting_list': Painting.objects.all()})
	elif (len(painting_list) == 0):
		return render(request, "ekart/index.html", {'error_message': 'No such painting exists. Please try with other words.', 'painting_list': Painting.objects.all()})
	else:
		return render(request, "ekart/results.html", {'painting_list': painting_list})

mysite/ekart/templates/ekart/detail.html
<h1>{{ painting.name }}</h1>

<h3>by {{ painting.artist.name }}</h3>
<img src="{{ painting.image.url }}" alt="{{ painting.name }}" style="height:300px;" />
<h4>Price: ${{ painting.price }}</h4> 

mysite/ekart/templates/ekart/index.html
{% if painting_list %}
	
	<form action="{% url 'ekart:search' %}" method="post">
	{% csrf_token %}
	<input type="text" name="t" id="searchbox" placeholder="Search">
	<input type="submit" value="Search">
	</form>
	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}
	<h1 style="text-align: center;">Paintings Available</h1>
	{% for painting in painting_list %}
		<ul style="list-style-type: none;">
			<li style="text-align: center; font-size: 25px;"><a href="{% url 'ekart:detail' painting.id %}">{{ painting.name }}</a></li>
			<div><img src="{{ painting.image.url }}" alt="{{ painting.name }}" style="height:300px; display:block; margin: auto;"/></div>
		</ul>
	{% endfor %}
{% else %}
	<h1>No paintings available</h1>
{% endif %}

mysite/ekart/templates/ekart/results.html
<h1 style="text-align: center;">Paintings matching your search</h1>

{% for painting in painting_list %}
	
	<ul style="list-style-type: none;">
		<li style="text-align: center; font-size: 25px;"><a href="{% url 'ekart:detail' painting.id %}">{{ painting.name }}</a></li>
		<img src="{{ painting.image.url }}" alt="{{ painting.name }}" style="height:300px; display: block; margin: auto;" />
	</ul>
{% endfor %}